common:
  appName: 'md'
  newtopic: 'newtopic'
plot_fonts:
  font:
    'family': 'serif'
    'color': 'darkred'
    'weight': 'normal'
    'size': 10

  # define font dictionary
  font_small:
    'family': 'serif'
    'color': 'darkred'
    'weight': 'normal'
    'size': 7

MDVariables:
  batchInterval: 2
  tickerWatch: "VOD"
  priceWatch: 300.0
  op_type: "1"
  op_type_API: "GET"
  currency: GBP
  tickerType: "short"
  tickerClass: "asset"
  tickerStatus: "valid"
  confidenceLevel: "1.645"
  zookeeperConnectionTimeoutM: "10000"
  zookeeperSessionTimeOutMs: "15000"
  sparkDefaultParallelism: "12"
  sparkSerializer: "org.apache.spark.serializer.KryoSerializer"
  sparkNetworkTimeOut: "3600"
  sparkStreamingUiRetainedBatches: "5"
  sparkWorkerUiRetainedDrivers: "5"
  sparkWorkerUiRetainedExecutors: "30"
  sparkWorkerUiRetainedStages: "100"
  sparkUiRetainedJobs: "100"
  sparkStreamingReceiverMaxRate: "0"
  sparkStreamingKafkaMaxRatePerPartition: "600"
  sparkStreamingBackpressurePidMinRate: "2000"
  schemaRegistryURL: "http://rhes75:8081"
  rebalanceBackoffMS: "15000"
  zookeeperConnectionTimeoutMs: "10000"
  autoCommitIntervalMS: "12000"
  topic: "md"
  newtopic: "newtopic"
  projectId: 'axial-glow-224522'
  datasetLocation: "europe-west2"
  targetDataset: "test"
  targetTable: "md"
  outputTable: targetDataset+"."+targetTable
  fullyQualifiedoutputTableId: projectId+":"+outputTable
  speedTable: targetDataset+"."+"mdspeed"
  fullyQualifiedspeedTableId: projectId+":"=speedTable
  tmp_bucket: "tmp_storage_bucket/tmp"
  DB: "test"
  rows_to_insert: "10"  
  movingAverages: 14
  confidenceLevel: 1.645
  targetSpeedTable: mdspeed
  mode: append
